name: Docker Image
on:
  push:
  pull_request:
    types:
      - closed
jobs:
  build:
    # if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'CI:TriggerBuild')}}
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout the Repository
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Set env
        run: echo "IMAGE_NAME=$(echo $(basename ${{ github.repository }}))" >> $GITHUB_ENV;echo "IMAGE_TAG=$(echo $(git describe --tags --always --dirty))" >> $GITHUB_ENV

      -
        name: Test env
        run: echo $IMAGE_NAME $IMAGE_TAG
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }},${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
